[project]
name = "Py-files"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "TAHA", email = "james@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.143.0",
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
    "pandas>=3.0.6",
    "pillow>=12.3.0",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "uvicorn[standard]>=0.54.0",
]

[tool.uv]
package = false
